# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'watermark_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toWatermarkList = QtWidgets.QListWidget(self.centralwidget)
        self.toWatermarkList.setObjectName("toWatermarkList")
        self.horizontalLayout.addWidget(self.toWatermarkList)
        self.toWatermarkButton = QtWidgets.QPushButton(self.centralwidget)
        self.toWatermarkButton.setObjectName("toWatermarkButton")
        self.horizontalLayout.addWidget(self.toWatermarkButton)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.watermarkFile = QtWidgets.QLabel(self.centralwidget)
        self.watermarkFile.setObjectName("watermarkFile")
        self.horizontalLayout_3.addWidget(self.watermarkFile)
        self.waterMarkFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.waterMarkFileButton.setObjectName("waterMarkFileButton")
        self.horizontalLayout_3.addWidget(self.waterMarkFileButton)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputFolder = QtWidgets.QLabel(self.centralwidget)
        self.outputFolder.setObjectName("outputFolder")
        self.horizontalLayout_4.addWidget(self.outputFolder)
        self.outputFolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.outputFolderButton.setObjectName("outputFolderButton")
        self.horizontalLayout_4.addWidget(self.outputFolderButton)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.CheckBoxContainer = QtWidgets.QVBoxLayout()
        self.CheckBoxContainer.setObjectName("CheckBoxContainer")
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.CheckBoxContainer)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setToolTip("")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.widthScale = QtWidgets.QLineEdit(self.centralwidget)
        self.widthScale.setObjectName("widthScale")
        self.horizontalLayout_2.addWidget(self.widthScale)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.heightScale = QtWidgets.QLineEdit(self.centralwidget)
        self.heightScale.setObjectName("heightScale")
        self.horizontalLayout_2.addWidget(self.heightScale)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.LabelRole, spacerItem)
        self.watermarkButton = QtWidgets.QPushButton(self.centralwidget)
        self.watermarkButton.setObjectName("watermarkButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.watermarkButton)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Files to Watermark"))
        self.toWatermarkButton.setText(_translate("MainWindow", "Choose"))
        self.label_3.setText(_translate("MainWindow", "Watermark To apply"))
        self.watermarkFile.setText(_translate("MainWindow", "Watermark"))
        self.waterMarkFileButton.setText(_translate("MainWindow", "Choose"))
        self.label_6.setText(_translate("MainWindow", "Output Folder"))
        self.outputFolder.setText(_translate("MainWindow", "Output"))
        self.outputFolderButton.setText(_translate("MainWindow", "Choose"))
        self.label_8.setText(_translate("MainWindow", "Watermark Location"))
        self.label_2.setText(_translate("MainWindow", "Image Scale:"))
        self.label_5.setText(_translate("MainWindow", "%W:"))
        self.widthScale.setText(_translate("MainWindow", "10"))
        self.label_4.setText(_translate("MainWindow", "% H:"))
        self.heightScale.setText(_translate("MainWindow", "10"))
        self.watermarkButton.setText(_translate("MainWindow", "Watermark"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

